# -*- coding: utf-8 -*-
"""ds102.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiLn0CYt582SfMHDLLk4QgkeOA-ZcyHY
"""

import pandas as pd

# -------- Extract --------
df = pd.read_csv('/content/customer_dataset.csv')

# -------- Transform --------
# Rellenar tipo de queja
df['tipo_de_queja'] = df['tipo_de_queja'].fillna('No clasificada')

# Variables binarias
df['descuento_aplicado'] = df['descuento_aplicado'].map({'Si': 1, 'No': 0})
df['aumento_ultimos_3_meses'] = df['aumento_ultimos_3_meses'].map({'Si': 1, 'No': 0})

# -------- Validaciones --------
assert df.isnull().sum().sum() == 0, "Existen valores nulos en el dataset final"
assert set(df['descuento_aplicado'].unique()) <= {0, 1}
assert set(df['aumento_ultimos_3_meses'].unique()) <= {0, 1}

# -------- Load --------
df.to_csv(
    'etl_dataset.csv',
    index=False,
    encoding='utf-8'
)